lb:
  ports:
  - 443:80
  - 80:80
  external_links:
  - ampache/ampache:ampache
  labels:
    io.rancher.loadbalancer.ssl.ports: '443'
    io.rancher.scheduler.affinity:host_label: web=true
  tty: true
  image: rancher/load-balancer-service
  stdin_open: true
